monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%-axpe-test.log'
            level: debug
            channels: [ '!event', '!doctrine' ]
            formatter: 'monolog.newline_formatter'

        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']

